modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Creative Commons"

[[mods]]
modId = "trulyheaven"
version = "${0.0.1}"
displayName = "JCraft: Truly Heaven"
authors = "Trayorkies"
description = '''
Heaven Stand Expansion Pack
'''
logoFile = "assets/trulyheaven/icon.png"

[[dependencies.trulyheaven]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trulyheaven]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trulyheaven]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.trulyheaven]]
modId = "jcraft"
mandatory = true
versionRange = "[0.17.0,)"
ordering = "AFTER"
side = "BOTH"
